### ISSUE TITLE
Can we use fsharp for this?

### ISSUE THREAD

**Issue by rishavs** [endlesstravel/Love2dCS#104]
Hi

I am new to the dotnet ecosystem. But can I use fsharp + dotnetcore 3.1 for your lib?

**Comment by endlesstravel** [comment]
yes. even, I've never used F#, but it's the same runtime(.net runtime), so i it work on it.
I used autocomplete to complete the program:
![image](https://user-images.githubusercontent.com/10757838/74714422-7cf7a380-5265-11ea-9020-01da312053a2.png)

**Comment by rishavs** [comment]
Thanks. I can confirm it is working for me too.

Here is my Programs.fs
```
namespace MyGame

module Program =

    open System
    open Love

    [<EntryPoint>]
    let main argv =
        Boot.Init();

        Boot.Run(Game());
        0 // return an integer exit code
```

and this is my Game.fs
```
namespace MyGame

open Love

type Game () as __ =
    inherit Scene()
 
    // override this.Load() =
    //     // TODO: Add your initialization logic here
        
    // override this.Update () =
    //     // TODO: Add your update logic here

    override this.Draw () =
        // TODO: Add your drawing code here
        Graphics.Print("Hello, World!", 400.0f, 300.0f);
```
Thank you. this is great!
