### ISSUE TITLE
question about using library with winforms

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#21]
i was just wondering how to create a love2d control in winforms?
just thought it would be cool to make a editor :D

**Comment by endlesstravel** [comment]
cool idea !

yes, we can embed a love2d window in winforms, it based on SDL2 , and we can embed SDL2 window to another window .

i am try to implement it , by re write a class of love::window::Window

**Comment by endlesstravel** [comment]
Frustratingly, it's hard to create SDL2 in an external window, but this might help :

http://forums.libsdl.org/viewtopic.php?t=9578&sid=090b706304f1829218c9c0f6887cce86

https://gamedev.stackexchange.com/questions/110205/context-is-null-with-sdl-createwindowfrom-win32

**Comment by Shadowblitz16** [comment]
idk if that would help or not, 
I have never embedded something in winforms before.

hopefully you can figure it out when you have time. :(

**Comment by endlesstravel** [comment]
There are two quick, flexible and safe solutions:
1. Create an in-game editor
2. Using the borderless Love2d window, let Love2d look like a child window of winform. This is the way, in the main window of winform to create a window called "Anchor plan", monitor the activation of the winform window and lose focus events, while changing the size of the Love2d window, listening to the Anchor plan" window changes, while changing love Window.

😂

**Comment by Shadowblitz16** [comment]
so then this really isn't going to happen then?

**Comment by Shadowblitz16** [comment]
wait i found this https://gist.github.com/flibitijibibo/cf282bfccc1eaeb47550
its how to hook a sdl window to a winforms panel

**Comment by endlesstravel** [comment]
I implement way 2,

 it need to file `Form1.cs ` and `LoveHookWin.cs`

code implement blow :

Form1.cs
```C#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsInner
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        LoveHookWin.WindowsStatus windowsStatus = new LoveHookWin.WindowsStatus();

        private void Form1_Load(object sender, EventArgs e)
        {
            windowsStatus.WinHeight = 800;
            windowsStatus.WinHeight = 600;
            new Thread(() =>
            {
                Love.Boot.Run(new LoveHookWin(windowsStatus));
            }).Start();
        }

        protected override void OnHandleCreated(EventArgs e)
        {
            base.OnHandleCreated(e);
        }

        private void button1_Click(object sender, EventArgs e)
        {
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {
        }

        void UpdatePlaneStatus()
        {
            windowsStatus.WinWidth = panel1.Size.Width;
            windowsStatus.WinHeight = panel1.Size.Height;
            var pos = panel1.PointToScreen(new Point());
            windowsStatus.WinX = pos.X;
            windowsStatus.WinY = pos.Y;
            windowsStatus.Changed = true;
        }

        private void Form1_Move(object sender, EventArgs e)
        {
            UpdatePlaneStatus();
        }

        private void Form1_Resize(object sender, EventArgs e)
        {
            UpdatePlaneStatus();
        }

        private void panel1_Resize(object sender, EventArgs e)
        {
            UpdatePlaneStatus();
        }

        private void panel1_Move(object sender, EventArgs e)
        {
            UpdatePlaneStatus();
        }

        private void Form1_Deactivate(object sender, EventArgs e)
        {
            windowsStatus.IsShow = false;
            UpdatePlaneStatus();
        }

        private void Form1_Activated(object sender, EventArgs e)
        {
            windowsStatus.IsShow = true;
            UpdatePlaneStatus();
        }

        private void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {
            windowsStatus.IsQuit = true;
        }
    }
}

```
LoveHookWin.cs
```C#
using System;
using Love;

namespace WindowsFormsInner
{
    public class LoveHookWin : Scene
    {
        public class WindowsStatus
        {
            public int WinX, WinY, WinWidth, WinHeight;
            public bool IsShow = true;
            public bool Changed = false;
            public bool IsQuit = false;
        }

        public readonly WindowsStatus Status;

        public LoveHookWin(WindowsStatus status)
        {
            Status = status;
        }

        public override void Load()
        {
            var mode = Window.GetMode();
            mode.borderless = true;
            mode.resizable = true;
            Window.SetMode(mode);
        }

        float t = 0;
        public override void Draw()
        {
            t = t + Timer.GetDelta();
            Graphics.Line(new Float2(), new Float2(t  * 20, t * 20));
            Graphics.Print("ha ha ha", 0, 0);
        }

        void ResponseWindowStatus(WindowsStatus status)
        {
            if (status.IsQuit)
            {
                Event.Quit(); // quit windows
            }

            if (status.Changed)
            {
                if (Window.GetFullscreen() == true)
                {
                    Window.SetFullscreen(false);
                }

                var mode = Window.GetMode();
                if (mode.borderless == false)
                {
                    mode.borderless = true;
                    Window.SetMode(mode);
                }

                WindowMover.Logic.Move(
                    Special.GetWin32Handle(), 
                    status.WinX, status.WinY, status.WinWidth, status.WinHeight,
                    status.IsShow || Window.HasMouseFocus() || Window.HasFocus() );
                status.Changed = false;
            }
        }

        public override void Update(float dt)
        {
            ResponseWindowStatus(Status);
        }
    }
}
namespace WindowMover
{
    using System.Runtime.InteropServices;

    static class Logic
    {
        [DllImport("user32.dll", EntryPoint = "MoveWindow")]
        public static extern bool MoveWindow(IntPtr hWnd, int x, int y, int w, int h, bool bRepaint);

        [DllImport("user32.dll", EntryPoint = "SetWindowPos")]
        public static extern IntPtr SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int x, int Y, int cx, int cy, uint wFlags);

        public static void Move(IntPtr handle, int x, int y, int width, int height, bool isShow)
        {
            const short SWP_NOMOVE = 0X2;
            const short SWP_NOSIZE = 1;
            const short SWP_NOZORDER = 0X4;
            const int SWP_SHOWWINDOW = 0x0040;
            const int SWP_HIDEWINDOW = 0x0080;
            const int SWP_NOSENDCHANGING = 0x0400;
            const int SWP_NOACTIVATE = 0x0010; // Does not activate the window. If this flag is not set, the window is activated and moved to the top of either the topmost or non-topmost group (depending on the setting of the hWndInsertAfter parameter).
            IntPtr HWND_TOPMOST = IntPtr.Subtract(IntPtr.Zero, 1); 
            //SetWindowPos(handle, HWND_TOPMOST, x, y, width, height, SWP_SHOWWINDOW | SWP_NOSIZE | SWP_NOMOVE);
            SetWindowPos(handle, HWND_TOPMOST, 0, 0, 0, 0, SWP_SHOWWINDOW | SWP_NOMOVE | SWP_NOSIZE);
            MoveWindow(handle, x, y, width, height, true);

            if (isShow == false)
            {
                SetWindowPos(handle, HWND_TOPMOST, 0, 0, 0, 0, SWP_HIDEWINDOW);
            }
        }
    }
}
```

**Comment by Shadowblitz16** [comment]
wow this is awesome thankyou!
so can this be implemented behind the scenes next update? 

however I would feel that making a abstract form to inherit from would be good as it would be easier to set up

```
class MyForm : LoveForm
{
    public MyForm() : base()
    {
    }
}
```

**Comment by endlesstravel** [comment]
No, this will be the a example to implement by developer.

Love2d is just a game engine not contain game editor.

the function `Special.GetWin32Handle()` will be find  at commit https://github.com/endlesstravel/Love2dCS/commit/376627aa4270de8386b17ea792346110877496cb .

it will be published at next update

**Comment by Shadowblitz16** [comment]
ok thankyou

**Comment by endlesstravel** [comment]
published : https://www.nuget.org/packages/Love2dCS/11.0.11

**Comment by Shadowblitz16** [comment]
@endlesstravel  so I have a question about the `Love.Special.GetWin32Handle()`
how exactly is it used?

**Comment by endlesstravel** [comment]
this function will return the [windows handle](https://stackoverflow.com/questions/902967/what-is-a-windows-handle/902973#902973) of the windows created(used) by love2d.

So you can use this handle to change the size, position, style of the window, etc. or something else.
![image](https://user-images.githubusercontent.com/10757838/58755925-6915e100-8520-11e9-967e-c27abbd4781c.png)

**Comment by Shadowblitz16** [comment]
@endlesstravel how would I implement it though?
do I just add it to the control like any other control or do I need to override a handle somewhere?

**Comment by endlesstravel** [comment]
As long as you have a handle, you can use these functions.
https://docs.microsoft.com/en-us/windows/desktop/winmsg/window-functions

They are not related to the WinForm system. 
This is some of the function related to windows platform.
This means you need learn more about windows api.

**Comment by Shadowblitz16** [comment]
so I tried doing this..

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using PE.Core;
using System.Threading;

namespace PE.Editor.Controls
{
    public partial class LoveView : Control
    {
        Control Control;

        public LoveView()
        {
            Control = FromHandle(Love.Special.GetWin32Handle());
            Controls.Add(Control);
        }
    }
}
```

however I get this error when trying to add it.
![image](https://user-images.githubusercontent.com/2453707/58756052-2f53c480-84a5-11e9-92b0-9418c4d9afc4.png)

I don't even know if I am doing it right.

**Comment by endlesstravel** [comment]
right, they are  [related to c & windows api ](https://stackoverflow.com/a/15773851). you need to learn about it. it just like : 

```C#
        [DllImport("user32.dll", EntryPoint = "MoveWindow")]
        public static extern bool MoveWindow(IntPtr hWnd, int x, int y, int w, int h, bool bRepaint);

        [DllImport("user32.dll", EntryPoint = "SetWindowPos")]
        public static extern IntPtr SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int x, int Y, int cx, int cy, uint wFlags);
```

the other way is to use plug-ins to help write code, here:
http://pinvoke.net/index.aspx

**Comment by Shadowblitz16** [comment]
so they are functions? how do I give them a body?
https://pastebin.com/xgw3PCzx

**Comment by endlesstravel** [comment]
![image](https://user-images.githubusercontent.com/10757838/58756619-ff510380-852e-11e9-9da1-059757b78f08.png)


ok, I can't answer your question. Please refer to other documents. The knowledge you need to know includes `window api calls` . and knowledge about `dll and C# calls`.

Based on [this answer](https://stackoverflow.com/a/2303835), I think you are not understand the use of `Control.FromHandle` . if you want adjust the style of the window, then you can't avoid the call of winapi.

* https://stackoverflow.com/questions/5010957/call-function-from-dll/15773851#15773851
* https://stackoverflow.com/questions/2285860/change-win32-window-style
* https://www.mono-project.com/docs/advanced/pinvoke

**Comment by Shadowblitz16** [comment]
sorry I will look at these

**Comment by Shadowblitz16** [comment]
@endlesstravel 
ok so I have one more question.
Is there a way to hook into the events of the Love.Special.GetWin32Handle()?

Like I would like to expose the load, update, and draw events for love;

**Comment by endlesstravel** [comment]
I can't understand what about the `hook` .
If you need to do two things at the same time, you can use multithreading. And attention that you can only draw on a love thread.
