### ISSUE TITLE
Question About supporting 2bpp pixel format 

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#33]
is it possible to convert a love2dcs imagedata to use a 2bpp pixel format?
that would be 2 bits per pixel which would be indexed color

**Comment by endlesstravel** [comment]
if you means : http://www.huderlem.com/demos/gameboy2bpp.html

here is an example:

```C#
    class Test2BPP : Scene
    {
        Image img;
        public static ImageData NewImageDataFrom2BPP(byte[] input)
        {
            if (input == null)
                throw new ArgumentNullException("bytes");

            if (input.Length != 16)
                throw new Exception("Invalid 2BPP format input");
                       
            var imgData = Image.NewImageData(8, 8);
            imgData.MapPixel((x, y, color) =>
            {
                var higher = input[y * 2 + 1];
                var lower = input[y * 2 + 0];
                var offset = 7 - x;
                var flag = 1 << offset;
                var num = (((higher & flag) >> offset) << 1) | (((lower & flag) >> offset) );
                float grey = (3 - num) / 3f;
                return new Vector4(grey, grey, grey, 1);
            });

            return imgData;
        }

        public override void Load()
        {
            var imgData = NewImageDataFrom2BPP(new byte[]
            {
                0xFF, 0x00, 0x7E, 0xFF, 0x85, 0x81, 0x89, 0x83, 0x93, 0x85, 0xA5, 0x8B, 0xC9, 0x97, 0x7E, 0xFF,
                //0x7C, 0x7C, 0x00, 0xC6, 0xC6, 0x00, 0x00, 0xFE, 0xC6, 0xC6, 0x00, 0xC6, 0xC5, 0x00, 0x00, 0x00
            });

            img = Graphics.NewImage(imgData);
            img.SetFilter(FilterMode.Nearest, FilterMode.Nearest);
        }


        public override void Draw()
        {
            Graphics.Clear(0, 0, 1, 1);
            Graphics.Draw(img, 0, 0, 0, 40, 40);
        }

        static void Main(string[] arg)
        {
            Boot.Run(new Test2BPP());
        }
    }
```

**Comment by Shadowblitz16** [comment]
why is it passing in 16 bytes? shouldn't it be a value 0f 0-3 per pixel?

**Comment by endlesstravel** [comment]
I generated an imageData in the data structure defined below : input a 16-byte array and output the image he represents

> "The Gameboy displays its graphics using 8x8-pixel tiles. As the name 2BPP implies, it takes exactly two bits to store the information about a single pixel. There are 64 total pixels in a single tile (8x8 pixels). Therefore, exactly 128 bits, or 16 bytes, are required to fully represent a single tile. As a result, any uncompressed graphics data present in a Gameboy ROM file is represented using exactly 16 bytes."
-- from http://www.huderlem.com/demos/gameboy2bpp.html

I still don't understand the input and output you expect.

**Comment by endlesstravel** [comment]
sorry, my English is not very good, i still can't figure out output and input that your expect.

so did you need to save a game capture drawing to a `Canvas` and save it to a NES 2bpp format ? or you want to load a Image from a NES 2bpp file ? or something else ?

**Comment by Shadowblitz16** [comment]
sorry this can be closed I was wrong about the nes storing tiles as bytes

**Comment by endlesstravel** [comment]
glad that you solved the problem.
