### ISSUE TITLE
Attempted to read or write protected memory

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#38]
hello I am getting this..
![image](https://user-images.githubusercontent.com/2453707/52925724-77305080-32e7-11e9-9d0a-d52eb71e66a8.png)

![image](https://user-images.githubusercontent.com/2453707/52925742-86af9980-32e7-11e9-966a-6c71f2e25746.png)

ZeldaMagic.Core.Game.cs

	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using Love;

	namespace ZeldaMagic.Core
	{
			class Boot : Scene
			{
					public static Game Game { get; set; }

					public static void Run(Game game)
					{
							Game = game;

							BootConfig Config   = new BootConfig();
							Config.WindowWidth  = 160;
							Config.WindowHeight = 144;

							var boot = new Boot();
							Console.Write(boot == null);
							Love.Boot.Run(boot, Config);
					}

					public override void Load()
					{
							Game.OnInit();
					}
					public override void Draw()
					{
							Game.OnTick();
					}
					public override bool Quit()
					{
							Game.OnExit();
							return true;
					}
			}
			public class Game
			{
					public static TileBank    TileBank    { get; set; }
					public static ComboBank   ComboBank   { get; set; }
					public static PaletteBank PaletteBank { get; set; }

					//Does nothing
					public static void Run(Game game)
					{
							TileBank    = new TileBank(16, 64, 8, 8);
							ComboBank   = new ComboBank(8, 32, 16, 16);
							PaletteBank = new PaletteBank(1, 256, 16, 1);
							Boot.Run(game);
					}

					//Hooks
					public virtual void OnInit() 
					{ }
					public virtual void OnTick() 
					{ }
					public virtual void OnExit() 
					{ }

					//Draw methods
					public static void DrawPalette(float x, float y, float w, float h, float scale = 1, uint index = 0, uint palette = 0)
					{

							//PaletteBank.Draw(x, y, w, h, scale, index, palette);
					}
					public static void DrawCombo  (float x, float y, float w, float h, float scale = 1, uint index = 0, uint palette = 0)
					{

							//ComboBank.Draw(x, y, w, h, scale, index, palette);
					}
					public static void DrawTile   (float x, float y, float w, float h, float scale = 1, uint index = 0, uint palette = 0)
					{

							//TileBank.Draw(x, y, w, h, scale, index, palette);
					}
			}
	}

ZeldaMagic.Engine.Program.cs

	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using System.Threading.Tasks;
	using ZeldaMagic.Core;

	namespace ZeldaEngine
	{

			public class Engine : Game
			{
					//Main
					public static void Main()
					{
							Run(new Engine());
					}

					public override void OnInit()
					{
							Tile tile = new Tile(16);
							tile.Import("stalfaux.png");
							TileBank.Add (new Tile(16));
							ComboBank.Add(new Combo(16));
					}
					public override void OnTick()
					{
							ComboBank.Draw(0, 0, 2, 2, 1, 0, 0);
					}
					public override void OnExit()
					{

					}
			}
	}

I am using latest version as of posting this.

**Comment by endlesstravel** [comment]
oops, it same that error occur when you attempte call  `Joystick.SetVibration`.

first try change code from  `Love.Boot.Run(boot, Config);` to 
```C#
    Love.Boot.Init(Config);
    Love.Boot.Run(boot);
```

`Joystick.SetVibration` work fine when you get an correct `Joystick` object.

So, it means that you get an incorrect `Joystick`.

So, the point is where did you get this `Joystick`  object from ?

need more detail about this issue.

the example code below is work fine on my machine: 
```C#
using System;
using Love;

namespace Test
{
    class Test : Scene
    {
        public override void JoystickAdded(Joystick joystick)
        {
            Console.WriteLine("JoystickAdded");
            joystick.SetVibration();
        }

        public override void JoystickReleased(Joystick joystick, int button)
        {
            Console.WriteLine("JoystickReleased");
            joystick.SetVibration();
        }

        public override void JoystickPressed(Joystick joystick, int button)
        {
            Console.WriteLine("JoystickPressed");
            joystick.SetVibration();
        }

        public override void JoystickHat(Joystick joystick, int hat, JoystickHat direction)
        {
            Console.WriteLine("JoystickHat");
            joystick.SetVibration();
        }

        public override void Draw()
        {
            var jys = Joystick.GetJoysticks();
            if (jys.Length > 0)
            {
                var joy = jys[0]; ;
                Graphics.Print("have a joystick");

                if (joy.IsDown(0))
                {
                    joy.SetVibration(1, 0, 1);
                }
                else
                {
                    joy.SetVibration();
                }
            }
            else
            {
                Graphics.Print("empty");
            }
        }
        public static void Main(string[] args)
        {
            BootConfig Config = new BootConfig();

            Love.Boot.Init(new BootConfig
            {
                WindowWidth = 160,
                WindowHeight = 144,
            });
            Love.Boot.Run(new Test());
        }
    }
}
```

**Comment by Shadowblitz16** [comment]
that's the thing I don't think I am using the joystick at all.
I haven't coded input whats so ever into my project yet.

also calling boot.init doesn't work it just changes the error a bit
	System.AccessViolationException
		HResult=0x80004003
		Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
		Source=<Cannot evaluate the exception source>
		StackTrace:
	<Cannot evaluate the exception stack trace>

![image](https://user-images.githubusercontent.com/2453707/52966920-5c002800-335d-11e9-8034-05df52c651c7.png)

**Comment by Shadowblitz16** [comment]
here is what it prints in the console...

	Falseinit shader code boot ...
	init shader code success
	FileSystem set source with path : C:\Users\Shadowblitz16\source\repos\ZeldaMagic
	\Engine\bin\x86\Debug
	Failed to initialize filesystem: already initialized
		 at Love.Love2dDll.CheckCAPIException(Boolean hasNoException)
		 at Love.Boot.Init(BootConfig bootConfig)
		 at Love.Boot.Run(Scene scene, BootConfig bootConfig)

**Comment by Shadowblitz16** [comment]
nevermind I found it I was trying to draw invalid data in my databank class

**Comment by endlesstravel** [comment]
ok !
