### ISSUE TITLE
Large deltas.

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#44]
hello for some reason I am getting deltas over 1 and trying to limit them with a accumulator makes them just add continuously  

    public class GameManager : Scene
    {
        Game   Game   { get; set; }
        Canvas Canvas { get; set; }

        int GameW     { get; set; } = 256;
        int GameH     { get; set; } = 240;
        int GameFps   { get; set; } = 30;
        int GameScale { get; set; } = 3;

        float UpdateAccumulator = 0.0f;
        float RenderAccumulator = 0.0f;

        public GameManager(Game game, int gameW, int gameH, int gameFps, int gameScale)
        {
            Game      = game;
            GameW     = gameW;
            GameH     = gameH;
            GameFps   = gameFps;
            GameScale = gameScale;
        }

        public override void Load()
        {
            Canvas = Graphics.NewCanvas(GameW, GameH);
            Canvas.SetFilter(FilterMode.Nearest, FilterMode.Nearest, 0);
            base.Load();
            Game.Create();
        }
        public override void Update(float dt)
        {
            UpdateAccumulator += dt;
            var limit = (1 / GameFps);
            if (UpdateAccumulator >= limit)
            {
                base.Update(dt);
                Game.Update();
                UpdateAccumulator -= limit;
            }
        }
        public override void Draw()
        {
            RenderAccumulator += Timer.GetDelta();
            var limit = (1 / GameFps);
            if (RenderAccumulator >= limit)
            {
                base.Draw();
                Graphics.SetCanvas(Canvas);
                Graphics.Clear(0, 0, 0);
                Game.Render();
                Graphics.SetCanvas();
                Graphics.Draw(Canvas, 0, 0, 0, GameScale, GameScale);
                RenderAccumulator -= limit;
            }
        }
    }

**Comment by endlesstravel** [comment]
I test the function `Timer.GetDelta()`, and it work fine. 

I can't figure out where something went wrong.

I need more information to locate the problem.

In addition, `base.Draw()`, `base.Update()`  and `base.Load()` is superfluous. 🙂

**Comment by Shadowblitz16** [comment]
here is my whole class ```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Love;

namespace BattleStars.Engine
{
    public class GameManager : Scene
    {
        Game   Game   { get; set; }
        Canvas Canvas { get; set; }

        int GameW     { get; set; } = 256;
        int GameH     { get; set; } = 240;
        int GameFps   { get; set; } = 30;
        int GameScale { get; set; } = 3;

        float UpdateAccumulator = 0.0f;
        float RenderAccumulator = 0.0f;

        public GameManager(Game game, int gameW, int gameH, int gameFps, int gameScale)
        {
            Game      = game;
            GameW     = gameW;
            GameH     = gameH;
            GameFps   = gameFps;
            GameScale = gameScale;
        }

        public override void Load()
        {
            Canvas = Graphics.NewCanvas(GameW, GameH);
            Canvas.SetFilter(FilterMode.Nearest, FilterMode.Nearest, 0);
            base.Load();
            Game.Create();
        }
        public override void Update(float dt)
        {
            UpdateAccumulator += dt;
            var limit = (1.0f / GameFps);
            //Console.WriteLine(UpdateAccumulator);
            if (UpdateAccumulator >= limit)
            {
                base.Update(dt);
                Game.Update();
                UpdateAccumulator -= limit;
            }
        }
        public override void Draw()
        {
            //RenderAccumulator += Timer.GetDelta();
            //var limit = (1 / GameFps);
            //if (RenderAccumulator >= limit)
            //{
                base.Draw();
                Graphics.SetCanvas(Canvas);
                Graphics.Clear(0, 0, 0);
                Game.Render();
                Graphics.SetCanvas();
                Graphics.Draw(Canvas, 0, 0, 0, GameScale, GameScale);
            //    RenderAccumulator -= limit;
            //}
        }
    }

    public class Game 
    {
        public static void Run(Game game, int gameW, int gameH, int gameFps, int gameScale)
        {
            BootConfig bootConfig   = new BootConfig();
            bootConfig.WindowWidth  = gameW * gameScale;
            bootConfig.WindowHeight = gameH * gameScale;
            Boot.Run(new GameManager(game, gameW, gameH, gameFps, gameScale), bootConfig);
        }

        public virtual void Create() { }
        public virtual void Update() { }
        public virtual void Render() { }
    }
}
```

**Comment by Shadowblitz16** [comment]
@endlesstravel you can mess with the gameFps to get buggy results.
it might be that visual studio was slowing it down or something but I do not actually have a precaution for large deltas so things like dragging the window makes the game speed up for a while

**Comment by endlesstravel** [comment]
if you want limit fps, you had wrong way to do that.

and Love limit the fps on 60. 

All i can do is increase the max fps limit or provide api to set max fps.

**Comment by Shadowblitz16** [comment]
it would be nice to have a way to set the game fps so that it doesn't go below or above

**Comment by endlesstravel** [comment]
okey, i will provide a method to set fps in next version.

**Comment by Shadowblitz16** [comment]
can't you could use a accumulator to make sure that the delta time was the same every frame?
and then sleep the remainder of the time?

**Comment by endlesstravel** [comment]
Yes, I can do this, but the delta time for each frame may not be "fully  identical". 

It may have some large frame time that make low FPS. 🔢 

And when you use 'Vertical Sync' option (default is opened),  the max fps is 60.

**Comment by endlesstravel** [comment]
now can use `Timer.EnableLimitMaxFPS` `Timer.DisableLimitMaxFPS` in version [11.0.24](https://www.nuget.org/packages/Love2dCS/11.0.24)

**Comment by Shadowblitz16** [comment]
ok cool thankyou
