### ISSUE TITLE
Mouse does not have a method for getting scroll wheel value

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#48]
Mouse does not have a method for getting scroll wheel value.
could something like this be implemented `public int Mouse.GetScrollValue()`
idk if its possible to do but a setter version of this would be nice as well 
`public void Mouse.SetScrollValue(int value)`

**Comment by endlesstravel** [comment]
okey, I will implement it in next version, which probably will published next week .
```C#
public static int Mouse.GetScrollX()
public static int Mouse.GetScrollY()
public static void Mouse.SetScrollX(int value)
public static void Mouse.SetScrollY(int value)
```

On the other hand, we have event to receive scroll message [love.wheelmoved](https://love2d.org/wiki/love.wheelmoved).
just like this:
```C#
using Love;
class Issue48: Scene
{
    string text = "";
    public override void WheelMoved(int x, int y)
    {
        if (y > 0)
        {
            text = "Mouse wheel moved up";
        }
        else if (y < 0)
        {
            text = "Mouse wheel moved down";
        }
    }

    public override void Draw()
    {
        Graphics.Print(text);
    }


    static void Main(string[] args)
    {
        Boot.Init(new BootConfig
        {
        });
        Boot.Run(new Issue48());
    }
}
```

**Comment by Shadowblitz16** [comment]
ok cool thankyou. 
I don't like using hooks because you can only really use them once in one place.
its better to have function to check these things

**Comment by endlesstravel** [comment]
now can use
```C#
Mouse.GetScrollX()
Mouse.GetScrollY()
Mouse.SetScrollX(int value)
Mouse.SetScrollY(int value)
```
in version [11.0.26](https://www.nuget.org/packages/Love2dCS/11.0.26)

**Comment by Shadowblitz16** [comment]
ok thankyou
