### ISSUE TITLE
Mouse GetXPrevious() and Mouse.GetYPrevious()

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#49]
could the following functions be implemented..\
`Mouse GetXPrevious()` 
`Mouse.GetYPrevious()`

they would be used to check if a mouse just moved to a position or not
these could be used to do gui enter and leave events without having to store mouse position per control

here is a example.. 
```
        public bool MouseJustEntered()
        {
            var mX    = ((int)Mouse.GetX());
            var mY    = ((int)Mouse.GetY());
            var mXOld = ((int)Mouse.GetPreviusX());
            var mYOld = ((int)Mouse.GetPreviusY());

            var checkX = (mX >= X && mX < X + W) && (mXOld < X || mXOld >= X + W);
            var checkY = (mY >= Y && mY < Y + H) && (mYOld < Y || mYOld >= Y + H);

            return (checkX && checkY);
        }
```

**Comment by endlesstravel** [comment]
Ok, You will find them in the next version, which probably will published next week .
But, I am not opposed to maintaining some state for each control, because you always have to maintain some state, it is inevitable. 😉

**Comment by Shadowblitz16** [comment]
this is great thankyou

**Comment by endlesstravel** [comment]
now can use
```C#
Mouse.GetPreviousX()
Mouse.GetPreviousY()
```
in version [11.0.26](https://www.nuget.org/packages/Love2dCS/11.0.26)

**Comment by endlesstravel** [comment]
The problem has been solved and no other activities have been carried out. so i close it.
