### ISSUE TITLE
Question about setting curser to system curser?

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#52]
I was just wondering how to set the curser to these?
https://love2d.org/wiki/CursorType

**Comment by endlesstravel** [comment]
just like below:
```C#
    Mouse.SetCursor(Mouse.GetSystemCursor(SystemCursor.Hand));
```

**Comment by Shadowblitz16** [comment]
ok I will try thankyou

**Comment by endlesstravel** [comment]
now we can do this like
```C#
Mouse.SetCursor(SystemCursor.Hand);
```
 in version 11.0.27,  and no other activities have been carried out. so i close it.
