### ISSUE TITLE
Love.Graphics.Rectangle is not pixel perfect after graphics.Scale()

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#54]
so I was making a gui library and scaling up the graphics before drawing my window by 4.0fx4.0f and then scaling back down gives me this..

![image](https://user-images.githubusercontent.com/2453707/57168043-e67cf300-6db4-11e9-8f3e-2b2dc8d57fde.png)

here is a example of my code..
```
        public override void Render()
        {
            base.Render();

            Graphics.Scale(4.0f, 4.0f);

            //WindowFrame Background
            Graphics.SetColor(new Color(63, 63, 63, 255));
            Graphics.Rectangle(DrawMode.Fill, X + 0, Y + 0, W - 0, H - 0);

            //WindowFrame Border
            Graphics.SetColor(new Color(33, 33, 33, 255));
            Graphics.Rectangle(DrawMode.Line, X + 0, Y + 0, W - 0, H - 0);
            Graphics.Rectangle(DrawMode.Line, X + 3, Y + 3, W - 6, H - 6);

            Graphics.SetColor(new Color(123, 123, 123, 255));
            Graphics.Rectangle(DrawMode.Line, X + 1, Y + 1, W - 2, H - 2);

            Graphics.SetColor(new Color(101, 101, 101, 255));
            Graphics.Rectangle(DrawMode.Line, X + 2, Y + 2, W - 4, H - 4);
            
            //Title Bar
            Graphics.SetColor(new Color(33, 33, 33, 255));
            Graphics.Rectangle(DrawMode.Fill, X + 1, Y +  0, W - 2, 16);
            Graphics.SetColor(new Color(240, 212, 149, 255));
            Graphics.Rectangle(DrawMode.Fill, X + 1, Y +  1, W - 2,  1);
            Graphics.SetColor(new Color(224, 169, 42, 255));
            Graphics.Rectangle(DrawMode.Fill, X + 1, Y +  2, W - 2, 13);
            Graphics.SetColor(new Color(168, 127, 31, 255));
            Graphics.Rectangle(DrawMode.Fill, X + 1, Y + 15, W - 2,  1);

            if (IsClicking())
            {
                Graphics.SetColor(new Color(255, 255, 255, 127));
                Graphics.Rectangle(DrawMode.Fill, X + 1, Y + 1, W - 2, 14);
            }
            else if (IsHovering())
            {
                Graphics.SetColor(new Color(255, 255, 255, 63));
                Graphics.Rectangle(DrawMode.Fill, X + 1, Y + 1, W - 2, 14);
            }

            Graphics.Scale(-4.0f, -4.0f);
        }
```

idk if this has to do with love2dcs or just love2d but it should be pixel perfect if scaling by 1x1 ratio right?

also when the window is inverted the drawing gets all messed up like this.. 
![image](https://user-images.githubusercontent.com/2453707/57168174-89ce0800-6db5-11e9-8419-9a7973e342ce.png)

**Comment by endlesstravel** [comment]
nice gui style, but here is an misunderstand.
if you scale up by  `Graphics.Scale(4.0f, 4.0f);` , scaling back down is not `Graphics.Scale(-4.0f, -4.0f);`
it should be `Graphics.Scale(0.25f, 0.25f);`

the other way is use `Graphics.Push()` & `Graphics.Pop()` to manage your transform state, you can checkout offical document: https://love2d.org/wiki/love.graphics.push

or just not use `Graphics.Scale(4.0f, 4.0f);` you calcuate scale coordinate by you self and floor the float to int value.

As for "pixel perfect", this is not an uncomplicated problem. I don't know the answer to this question, this is an question about love2d. what i can say is love2d was not "pixel perfect" automatically. so you need do something yourself.
There was a discussion on this in the forum:
https://love2d.org/forums/viewtopic.php?f=4&t=80579&p=186872

**Comment by Shadowblitz16** [comment]
hmm ok I will try these out thankyou
