### ISSUE TITLE
Suggestion more Vector2 properties and Rotate 

### ISSUE THREAD

**Issue by Picalines** [endlesstravel/Love2dCS#56]
It would be helpful to have more Vector2 properties:
Vector2 Right => new Vector2(1, 0);
Vector2 Left => new Vector2(-1, 0);
Vector2 Up => new Vector2(0, -1);
Vector2 Down => new Vector2(0, 1);

Also Vector2.Rotate function:
public static Vector2 Rotate(Vector2 vec, float angle) {
  return new Vector2 {
    X = Mathf.Cos(angle * vec.x) - Mathf.Sin(angle * vec.y),
    Y = Mathf.Sin(angle * vec.x) + Mathf.Cos(angle * vec.y)
  };
}

**Comment by endlesstravel** [comment]
That sounds reasonable, but the rotation function looks problematic. 
Does your rotation function have other intentions, or is it just a mistake? (+_+)?
I make a change, add the Vector.RotateRadian, the way to implement Rotate :
```C#
        /// <summary>
        /// Calculate the new position of the point after the counterclockwise rotation angle(degrees).
        /// </summary>
        /// <param name="v">the base point</param>
        /// <param name="degrees">the degrees to rotate</param>
        /// <returns></returns>
        public static Vector2 Rotate(Vector2 v, float degrees)
        {
            float radians = degrees * Mathf.Deg2Rad;
            float sin = Mathf.Sin(radians);
            float cos = Mathf.Cos(radians);
            float tx = v.x;
            float ty = v.y;
            v.x = (cos * tx) - (sin * ty);
            v.y = (sin * tx) + (cos * ty);
            return v;
        }

        /// <summary>
        /// Calculate the new position of the point after the counterclockwise rotation angle(radin).
        /// </summary>
        /// <param name="v">the base point</param>
        /// <param name="radin">the radian to rotate</param>
        /// <returns></returns>
        public static Vector2 RotateRadian(Vector2 v, float radin)
        {
            float sin = Mathf.Sin(radin);
            float cos = Mathf.Cos(radin);
            float tx = v.x;
            float ty = v.y;
            v.x = (cos * tx) - (sin * ty);
            v.y = (sin * tx) + (cos * ty);
            return v;
        }
```
As for "up and down", I'm not going to provide them to avoid misunderstanding. ...where `Vector2.Up` is (0, 1) for screen coordinates or `Vector2.Up` maybe (1, 0) for world coordinates.

If you insist to add `Vector2.Up`, I intend to set the `Vector2.Up` to (0,1) and the `Vector2.Down` to (0, -1), because Vector3.Up is (0, 1, 0), I want to keep it uniform. 

 What do you think?

**Comment by Picalines** [comment]
Maybe you can add something like `Vector2.ScreenUp` (0, -1) and `Vector2.WorldUp(0, 1)`? 
Rotate functions that you offered seems good addition

**Comment by endlesstravel** [comment]
Smart solutions !
so, how about this ? :
```C#
        public static Vector2 ScreenRight => new Vector2(1, 0);
        public static Vector2 ScreenLeft => new Vector2(-1, 0);
        public static Vector2 ScreenUp => new Vector2(0, -1);
        public static Vector2 ScreenDown => new Vector2(0, 1);
        public static Vector2 WorldRight => new Vector2(1, 0);
        public static Vector2 WorldLeft => new Vector2(-1, 0);
        public static Vector2 WorldUp => new Vector2(0, 1);
        public static Vector2 WorldDown => new Vector2(0, -1);
```

**Comment by matej-zajacik** [comment]
What would `World*` be good for? We're always working in screen space with vectors, if I'm not mistaken; or is there a use case for that?

**Comment by endlesstravel** [comment]
ok, It seems that I think too much. i mean, some man when custom their own camera, but , you are right, people more like use it on screen space. so how about this ?
```C#
        public static Vector2 Right => new Vector2(1, 0);
        public static Vector2 Left => new Vector2(-1, 0);
        public static Vector2 Up => new Vector2(0, -1);
        public static Vector2 Down => new Vector2(0, 1);
```

**Comment by endlesstravel** [comment]
now can use `Vector2.Rotate` `Vector2.Left`  `Vector2.Right`  `Vector2.Down`  `Vector2.Up`
in version [11.0.27](https://www.nuget.org/packages/Love2dCS/11.0.27)
