### ISSUE TITLE
How do I create a bitmap font?

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#6]
can you explain how to create a bitmap font?
I currently have this however I am not sure how to pass in the glyphs

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Love;

    namespace ZeldaEngine.Editor.Widgets
    {
        public class Button : Widget
        {
            FileData FontData;
            Font     Font;

            public Button(Widget parent, float x, float y, float w, float h) : base(parent, x, y, w, h)
            {
                IsDraggable = false;

                FontData = FileSystem.NewFileData("C:\\Users\\Shadowblitz16\\source\\repos\\ZeldaEngine\\ZeldaEngine\\Resources\\GB_Font.png");
                Font = Graphics.NewFont(Font.NewBMFontRasterizer(FontData, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcedfghijklmnopqrstuvwxyz1234567890_+-={}|[]\\:\";'<>?,./"); //this gives a compile error 
            }
        }
    }

**Comment by endlesstravel** [comment]
Below give an example of how to use TTF font and PNG Font.

Image :

![https://love2d.org/w/images/thumb/6/67/Resource-Imagefont.png/800px-Resource-Imagefont.png](https://love2d.org/w/images/thumb/6/67/Resource-Imagefont.png/800px-Resource-Imagefont.png "font")
--

```C#
﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using fs = Love.FileSystem;
using au = Love.Audio;
using sd = Love.Sound;

using Love;

namespace ConsoleApplication1
{
    class Program : Love.Scene
    {
        Font font;
        Font imageFont;

        public static Font NewFont(String filename)
        {
            var fileData = FileSystem.NewFileData(filename);
            var rasterizer = Font.NewRasterizer(fileData);
            return Graphics.NewFont(rasterizer);
        }

        public static Font NewImageFont(String filename, String glyphs, int extraspacing = 0)
        {
            var imageData = Image.NewImageData(filename);
            System.Text.Encoding utf8 = System.Text.Encoding.GetEncoding("utf-8");
            var glyphsBytes = utf8.GetBytes(glyphs);
            var rasterizerImage = Font.NewImageRasterizer(imageData, glyphsBytes, extraspacing);
            return Graphics.NewFont(rasterizerImage);
        }

        public override void Load()
        {
            font = NewFont("NotoSansHans-Regular.otf");
            imageFont = NewImageFont("Resource-Imagefont.png",
                " abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,!?-+");

        }

        public override void Update(float dt)
        {
        }

        public override void Draw()
        {
            Graphics.Clear(255, 255, 255, 255);

            Graphics.SetColor(0, 0, 0);
            Graphics.SetFont(font); // set font with OTF
            Graphics.Print("你好", 0, 0);

            Graphics.SetColor(255, 255, 255);
            Graphics.SetFont(imageFont);
            Graphics.Print("This is a test text", 0, 50);
            Graphics.Print("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789?.,", 0, 100);
        }

        static void Main(string[] args)
        {
            Boot.Run(new Program());
        }
    }
}
```

**Comment by Shadowblitz16** [comment]
thankyou so much this was really confusing

**Comment by endlesstravel** [comment]
yes, it really confusing, next update will make function convenient to use.

**Comment by Shadowblitz16** [comment]
awesome

**Comment by endlesstravel** [comment]
something wrong here.

I use font.NewImageRasterizer here to create a new font object, however LÖVE  not support this function.

![image](https://user-images.githubusercontent.com/10757838/46159422-e19e1100-c2b2-11e8-8f11-3928813b4888.png)

So the right way to do this should create font with `BMFont` , you can generate bitmap fonts from TrueType fonts with [BMFont - AngelCode.com](http://www.angelcode.com/products/bmfont/) .

my-img-font.fnt :

![image](https://user-images.githubusercontent.com/10757838/46159299-8e2bc300-c2b2-11e8-8046-82aaf31234c9.png)

and images : 

![image](https://user-images.githubusercontent.com/10757838/46159270-77856c00-c2b2-11e8-8169-829d192434c0.png)

lua code:

![image](https://user-images.githubusercontent.com/10757838/46159741-9afce680-c2b3-11e8-964b-e227ee2013f9.png)
