### ISSUE TITLE
Trying to send a variable value to the shader, doesn't work

### ISSUE THREAD

**Issue by Terisback** [endlesstravel/Love2dCS#62]
Trying to send a variable value
`lightRenderShader.Send("xresolution", new int[] { light.size });`
![image](https://user-images.githubusercontent.com/26527529/57703404-6fc7db80-7679-11e9-8acc-ebfd9da3ca0f.png)
Getting error
![image](https://user-images.githubusercontent.com/26527529/57703536-aef62c80-7679-11e9-9367-2192abc19594.png)
Is it even possible?

**Comment by Terisback** [comment]
Here is the code for this file.
https://github.com/Terisback/AvoBooba/blob/master/AvoBooba/sources/LightTest.cs

**Comment by endlesstravel** [comment]
ok, try this,
```C#            
            lightRenderShader.Send("xresolution", (float)light.size);
            shadowMapShader.Send("yresolution", (float)light.size);
```
 because your type of `xresolution` is number, it need pass float value.

**Comment by endlesstravel** [comment]
And i check your code and.. your code have bug on create canvas, you shouldn't create the canvas each frame ! (this will lead an error !)
you should change the code from (in method `DrawLight`) : 
```C#
            light.occludersCanvas = Graphics.NewCanvas();
            light.shadowMapCanvas = Graphics.NewCanvas();
            light.lightRenderCanvas = Graphics.NewCanvas();
```
to 
```C#
            if (light.occludersCanvas == null)
                light.occludersCanvas = Graphics.NewCanvas();
            if (light.shadowMapCanvas == null)
                light.shadowMapCanvas = Graphics.NewCanvas();
            if (light.lightRenderCanvas == null)
                light.lightRenderCanvas = Graphics.NewCanvas();
```
（￣︶￣）↗

**Comment by Terisback** [comment]
Thank you, it does not display errors.
But now I realized that my attempts to adapt the light from this script
https://github.com/Terisback/AvoBooba/blob/master/AvoBooba/sources/LightTest.cs
were not successful.
![Waaa](https://user-images.githubusercontent.com/26527529/57773418-6d28bd00-7731-11e9-9011-a946ed49e82a.gif)

**Comment by Terisback** [comment]
Ohh, f*ck it's working... kinda... without shadows, but the LIGHT!
![image](https://user-images.githubusercontent.com/26527529/57774248-71ee7080-7733-11e9-8b0f-96ab808788a8.png)
All I need it's to do like in the original script
![image](https://user-images.githubusercontent.com/26527529/57774271-829ee680-7733-11e9-9fe4-70df77169769.png)

**Comment by Terisback** [comment]
aaeee, it's working
![image](https://user-images.githubusercontent.com/26527529/57774354-c396fb00-7733-11e9-8360-59188c7d08cd.png)
by this
![image](https://user-images.githubusercontent.com/26527529/57774368-cb569f80-7733-11e9-9ba6-19cacf9c322d.png)

**Comment by Terisback** [comment]
Thank you @endlesstravel 
![image](https://user-images.githubusercontent.com/26527529/57774832-00afbd00-7735-11e9-871b-b4ef8bb52e8a.png)
