### ISSUE TITLE
11.0.29 Crash in Boot.Init()

### ISSUE THREAD

**Issue by matej-zajacik** [endlesstravel/Love2dCS#64]
I just updated to 11.0.29 and the framework crashes right at the start, when calling `Boot.Init()`.

![image](https://user-images.githubusercontent.com/8986611/57985612-b26b2880-7a6a-11e9-9c16-ce6869eaa7ed.png)

System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=Love2dCS
  StackTrace:
   at Love.Love2dDll._wrap_love_dll_open_love_math()
   at Love.Boot.Init(BootConfig bootConfig)
   at Game.Program.Main(String[] args) in E:\MyDocs\Love2DCS\TestProjects\DocsTutorial_HelloWorld\DocsTutorial_HelloWorld\Program.cs:line 10

**Comment by endlesstravel** [comment]
it looks like that your program load x86 native library on x64 .net platform (or  load x64 native library on x86 platform).
I test by my self, and it work fine. 
so i can't figure out what happened. 
It may have something to do with your configuration ?

**Comment by matej-zajacik** [comment]
That's weird. I didn't change any settings, just updated Love2dCS to 11.0.29. I'm still targeting the x64 platform as before.

Now, I tried to create a new, clean project, installed Love2dCS 11.0.29 via NuGet, set the platform to x64, and I'm still getting the same error. I had no such issues before.

Are the steps to create a new project to work with Love2dCS still the same, or did something change?

**Comment by endlesstravel** [comment]
The build script has changed to support `dotnet core 2` since `11.0.28`. So if there is a problem, there should be a problem from version `11.0.28`.

I recommend that you install the `11.0.28` version first.
And try to install their `dotnet core 2` version to determine the problem.

here is step to install `.net core` version:
```shell
dotnet new console
dotnet add package Love2DCS
```
add `<Platform>x64</Platform>` to your .csproj file, it should be look like :
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <Platform>x64</Platform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Love2DCS" Version="11.0.29" />
  </ItemGroup>

</Project>
```
the run the project
```shell
dotnet run
```

**Comment by endlesstravel** [comment]
ok, i reproduce  the problem on virtual machine, i will try to fix that

**Comment by matej-zajacik** [comment]
Thank you!

Oh, so now Love2dCS runs on .NET Core as well? That's great!

**Comment by endlesstravel** [comment]
yes, i  add the .net core support "stealthily".  but it still can only run windows platform. unexpectedly, this lead a bug. 😅
now i try fix the problem on [11.0.30](https://www.nuget.org/packages/Love2dCS/11.0.30), it already work fine on my virtual machine.
but I not sure if it's successful. waiting anxiously for your feedback.  👀

**Comment by matej-zajacik** [comment]
Haha... Thank you for the quick fix! I'll test it as soon as I get home.

**Comment by matej-zajacik** [comment]
Great! Works like a charm under .NET Core 2.2! Thank you!
