### ISSUE TITLE
Matrix44 multiplication

### ISSUE THREAD

**Issue by jpayne36** [endlesstravel/Love2dCS#66]
I looked in your source code and saw that you implemented matrix multiplication but I can't access those functions in my program

**Comment by jpayne36** [comment]
Okay thank you, I'm trying to render 3D objects using a shader and those matrix functions are helpful.

**Comment by endlesstravel** [comment]
You are welcome.  it was a interesting idea.
I add the `Matrix44` `Matrix33` `Matrix44` function and  push the [11.0.31-alpha](https://www.nuget.org/packages/Love2dCS/11.0.31-alpha) (Wait it indexed before you install it)
This is the preview version, so if you don't turn on the switch`include pre-release packages`, it won't appear in the list. : https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages
![image](https://user-images.githubusercontent.com/10757838/58259246-be2a5800-7da6-11e9-8299-b9158f388ff1.png)

If everything is all right, then it will appear in the normal version. 😃
