### ISSUE TITLE
Embedded Assemblies?

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#7]
is it possible to embed these assemblies?
![image](https://user-images.githubusercontent.com/2453707/45931685-401b6600-bf26-11e8-974a-d8b82285363b.png)
I would like them to not show up in my project output, however I don't know if I can do this since they are a output from Love2dCS.dll and not my project.

**Comment by endlesstravel** [comment]
These files need to be included in the output file, and they provide the capabilities of the Love engine.

There should be some way to do this, emm...,  but I don't know how to do.

**Comment by Shadowblitz16** [comment]
I saw this video here https://www.youtube.com/watch?v=x-KK7bmo1AM thats why I was asking.

**Comment by endlesstravel** [comment]
awesome, emm .., it give us a way to embed and reference an external assembly, but those dll file is managed dll.

Love2dCS.dll can embed as this way. 

but  `love.dll` / `lua51.dll` / `mpg123` / `OpenAL32.dll` / `SDL2.dll` is unmanaged dll. And i import function with `DllImport[xxx] `.  it means i can't receive a `AssemblyResolve` event.

And i need to load library by win32 api :  LoadLibrary  https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx

I think this is another solution: https://stackoverflow.com/questions/666799/embedding-unmanaged-dll-into-a-managed-c-sharp-dll

**Comment by Shadowblitz16** [comment]
oh cool so this might be implemented? :D

**Comment by endlesstravel** [comment]
maybe , but not now, there are other more important things to do, such as improving testing and ensure all functions are reliable..

**Comment by Shadowblitz16** [comment]
cool thankyou!
I realize this really wasn't a issue, 
but I have massive ocd and I just bothered me a bit.
