### ISSUE TITLE
How Do I convert Love Resources to System Resources?

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#70]
How Do I convert the following?.. 
- ImageData **to** and **from** System.Drawing.Bitmap
- Source **to** and **from** System.Media.SoundPlayer

**Comment by Terisback** [comment]
I can reference my issue that describes how convert bitmaps to image data.
https://github.com/endlesstravel/Love2dCS/issues/25

**Comment by Shadowblitz16** [comment]
thankyou

**Comment by Shadowblitz16** [comment]
@Terisback
I just realized yours uses filepath in which I need to actully convert a system.drawing.bitmap to a love.imageData.

**Comment by Terisback** [comment]
Sorry, I don't know how I can help

**Comment by endlesstravel** [comment]
thank @Terisback
close for no response for a long time
