### ISSUE TITLE
Vector2.Normalized

### ISSUE THREAD

**Issue by matej-zajacik** [endlesstravel/Love2dCS#71]
Currently, if you need a normalized **copy** of a [Vector2](https://github.com/endlesstravel/Love2dCS/blob/master/csharp_src/Love.Vector2.cs), you need to:

```C#
var v = new Vector2();
var normalizedV = Vector2.Normalize(v);
```

I suggest to add a handy "shortcut" function :

```C#
public Vector2 Normalized()
{
    return Vector2.Normalize(this);
}
```

Or make it inline, whichever is better.

So the previous example would go like this:

```C#
var v = new Vector2();
var normalizedV = v.Normalized();
```

This is inspired by Unity's vector structures, which I'm using daily in my job. It's quite natural to use: https://docs.unity3d.com/ScriptReference/Vector3-normalized.html

**Comment by endlesstravel** [comment]
ok, I'll add it.  I think it's silly to lack this function myself.
