### ISSUE TITLE
Vector2.X vs Vector2.x

### ISSUE THREAD

**Issue by matej-zajacik** [endlesstravel/Love2dCS#72]
[Vector2](https://github.com/endlesstravel/Love2dCS/blob/master/csharp_src/Love.Vector2.cs) starts with defining the fields:

```C#
public float X;
public float Y;
```

...and then continues to implement these properties:

```C#
public float x
{
    get { return X; }
    set { X = value; }
}

public float y
{
    get { return Y; }
    set { Y = value; }
}
```

I find two issues here:

1. The properties serve no purpose, as they implement no logic other than simply getting and setting the fields. Accessing the fields directly produces the same exact result.
1. The naming of the properties is odd. Properties in almost all C# APIs are written in PascalCase, whereas these are written in camelCase. I understand that you had to name them something else than the fields, but that only indicates that they are redundant.

I suggest to remove the properties.

**Comment by endlesstravel** [comment]
ok, despite the risk of removing existing code, this is much better than changing the definition of a function, I intend to remove them.

**Comment by matej-zajacik** [comment]
Yeah, there's the drawback of possibly breaking somebody's code by removing the props. But the result will be cleaner, I think.

**Comment by Shylie** [comment]
Vector4 has this same issue.

**Comment by endlesstravel** [comment]
@Shylie . ok, i will fix it.
