### ISSUE TITLE
is love2dcs cross platform when using .net core 2?

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#74]
I have a simple question.
is love2dcs cross platform when using .net core 2?

**Comment by endlesstravel** [comment]
no, it only work on windows platform .

**Comment by Shadowblitz16** [comment]
ahh ok that's too bad hopefully in the future it will be cross platform

**Comment by endlesstravel** [comment]
Okay, maybe he'll be able to do it in the future, but maybe it shouldn't be urgent.

**Comment by zhengying** [comment]
Hi, any update?  is macOS supported?
if not, so pity, so many love2d developers use macOS.

**Comment by endlesstravel** [comment]
@zhengying 
> Hi, any update? is macOS supported?
> if not, so pity, so many love2d developers use macOS.

yes, the nuget package test passed on MacOS 10.13 with dotnet core

**Comment by endlesstravel** [comment]
Love2dCS( LoveSharp ) now support : 
windows-x86 / windows-x64 / ubuntu-16 x64 / ubuntu-18 x64 / MacOS 10.12+ x64 with .net startard 1.2 (.NET Core | .NET Framework 4.5.1 | Mono 4.6
