### ISSUE TITLE
Mathf.Random uses same seed

### ISSUE THREAD

**Issue by Shylie** [endlesstravel/Love2dCS#79]
Every time I launch my program, the same random values are returned. This probably means that Mathf.Random is using the same seed every time.

EDIT: `Mathf.Ext_getRandomGenerator().SetSeed(uint low, uint high)` works, but it's rather inconvenient to have to include it. Perhaps a call to that could be added in the `Mathf.Init()` static method?

**Comment by endlesstravel** [comment]
You're right. i agree with you. and i will add overloaded of :
```C#
Mathf.Init(long seed)
```
and 
```C#
long RandomGenerator.GetSeed();
RandomGenerator.SetSeed(long value)
```
but considering that the `Math. Init` is rarely manual called.

So i will add `long? DefaultRandomSeed` in `BootConfig`.

**Comment by endlesstravel** [comment]
closed because it finished .
