### ISSUE TITLE
Use C# events to hook things like Love.Load, love.Update

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#83]
Can love hooks be made to work with events?

aka
```
Scene.Load   += MyClass.Init;
Scene.Update += MyClass.Tick;
Scene.Draw   += MyClass.Draw;
```
this also has to do with https://github.com/endlesstravel/Love2dCS/issues/82

**Comment by endlesstravel** [comment]
you can use `Scene.OnXXXX` at version `11.0.44` https://www.nuget.org/packages/Love2dCS/11.0.44

**Comment by Shadowblitz16** [comment]
cool thankyou
