### ISSUE TITLE
ImageData:GetPixel() and ImageData:SetPixel() should return Colors instead of pixels

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#84]
ImageData:GetPixel(),
ImageData:SetPixel(), 
ImageData:GetPixels(),
ImageData:SetPixels(), 

should return a Color instead of the Pixel class

**Comment by endlesstravel** [comment]
It had change it arguments/return type to `Color` at version 11.0.39 https://www.nuget.org/packages/Love2dCS/11.0.39

the old function rename to `SetPixelsRaw` `GetPixelsRaw` `SetPixelRaw` `GetPixelRaw`

**Comment by endlesstravel** [comment]
closed because it's finished.
