### ISSUE TITLE
MouseButtons should be a enum

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#85]
MouseButtons should be a enum instead of constants in the Mouse class

**Comment by endlesstravel** [comment]
ok, i already add them by:
```C#
        public bool IsDown(MouseButton btn) => IsDown((int)btn);
        public bool IsPressed(MouseButton btn) => IsPressed((int)btn);
        public bool IsReleased(MouseButton btn) => IsReleased((int)btn);
```
in version [11.0.45](https://www.nuget.org/packages/Love2dCS/11.0.45)

**Comment by Shadowblitz16** [comment]
no I mean like the MouseButton enum should derive for int or uint...```cs
public enum MouseButton : int {}```
