### ISSUE TITLE
using costura fody to embed these dlls?

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#88]
do you think costura fody could be used to embed the 3rd party love dlls?

![image](https://user-images.githubusercontent.com/2453707/64082523-4cc34500-ccc5-11e9-8b37-02af9d8a22e0.png)

I can only seem to get it to work with love.dll
however maybe you can get it to work with the others

**Comment by Shadowblitz16** [comment]
it might better to wrap the unmanaged c++ dlls into a managed C# one so that something like fody can be used with love2d.

**Comment by Shadowblitz16** [comment]
this is the result of a discussion about how to embed native dlls into a managed library with a user called abnormal.

[EmbeddedNative-Love2dCS.zip](https://github.com/endlesstravel/Love2dCS/files/3572423/EmbeddedNative-Love2dCS.zip)

It embeds the following..
love.dll
lua51.dll
mpg123.dll
OpenAL32.dll
SDL2.dll

**Comment by endlesstravel** [comment]
good idea. i'm not use the costura, but i get the same effect. now it will release native library to temp folder. 
 [11.0.37](https://www.nuget.org/packages/Love2dCS/11.0.37).

**Comment by endlesstravel** [comment]
closed because it finished .
