### ISSUE TITLE
Error when running application OS X

### ISSUE THREAD

**Issue by Bambofy** [endlesstravel/Love2dCS#90]
Hi, i'm trying to install and use this using Visual studio 2019 preview for Mac (https://visualstudio.microsoft.com/vs/mac/) and .net core 3.1.

It compiles fine but when it executes this is the message it returns?

<img width="1350" alt="Screenshot 2019-11-04 at 20 51 38" src="https://user-images.githubusercontent.com/1304898/68157120-f2ed2e80-ff44-11e9-93b1-b31ade302f67.png">

**Comment by endlesstravel** [comment]
Unfortunate, this library is only support win & ubuntu(debain serial).

**Comment by Bambofy** [comment]
> Unfortunate, this library is only support win(x86/64) & ubuntu(debain serial x64).
> 
> But, Now that someone's asked, I'll try to add Mac to the support in the near future

thank you! do you know how long it will take to be supported? i thought .net core was cross platform?

**Comment by endlesstravel** [comment]
I expect to finish the plan in a month. But since I have never used MAC for development, it's hard to say what will happened.

 .net core self is cross platform. But in this project, i use `P/invoke` to call unmanaged native code, so each platform should build it own native code. This is the reason this library not `cross platform`

**Comment by endlesstravel** [comment]
good news, 11.0.41-alpha now support the MacOS, it should be work on MacOS 10.7+

here : https://www.nuget.org/packages/Love2dCS/11.0.41-alpha

I test it on `.net core 3.0`, it should work on `.net core 1.0+`, it shoud be support dev on `visual studio for mac` too.

I will split the Love2dCS to `Love2dCS` `Love2dCS-ubuntu` `Love2dCS-mac` for the package size  to large, which is 17.3 MB now .

**Comment by Bambofy** [comment]
thanks :)

**Comment by Bambofy** [comment]
I tried to run a built application
 using the love2dcs-mac package and got this error:

<img width="1382" alt="Screenshot 2019-11-09 at 09 24 11" src="https://user-images.githubusercontent.com/1304898/68526347-b322a000-02d2-11ea-8e9c-7dd231c8147f.png">

**Comment by endlesstravel** [comment]
ok , thanks for your report! 👍 
I have deleted all my local dependency libraries cache, which will reproduce your problem.  
I probably know how to fix it, and I'll fix them.

**Comment by Bambofy** [comment]
ok thanks :)

**Comment by endlesstravel** [comment]
I fix it at `Love2dCS-mac` on version `11.0.42-beta`  on https://www.nuget.org/packages/Love2dCS-mac/11.0.42-beta 
Check "view preview package" at `Manage Nuget Packages` windows and you should see the `beta` version.

**Comment by Bambofy** [comment]
> I fix it at `Love2dCS-mac` on version `11.0.42-beta` on https://www.nuget.org/packages/Love2dCS-mac/11.0.42-beta
> Check "view preview package" at `Manage Nuget Packages` windows and you should see the `beta` version

Thank you very much for fixing it, this library is epic!!!

**Comment by endlesstravel** [comment]
closed because it finished .
