### ISSUE TITLE
Love.Graphics.SetScisser() doesn't support nested clipping

### ISSUE THREAD

**Issue by Shadowblitz16** [endlesstravel/Love2dCS#93]
I am having a problem where love2dcs isn't clipping the second clipping rectangle to the first

what I would expect would that nested scissers combine to clip to the first

here is a example of what it does..
![image](https://user-images.githubusercontent.com/2453707/68723300-044dc080-056d-11ea-8578-f26702f24c2a.png)

here is a example of what I think it should do..
![image](https://user-images.githubusercontent.com/2453707/68723494-8b029d80-056d-11ea-8952-62d5a4b1c216.png)

**Comment by endlesstravel** [comment]
please check out `Graphics.IntersectScissor`, i think this is what you want : https://love2d.org/wiki/love.graphics.intersectScissor

**Comment by Shadowblitz16** [comment]
ahh ok this is a little weird but it will do. thankyou.

**Comment by Shadowblitz16** [comment]
@endlesstravel is there a way to disable a nested Graphics.IntersectScissor()?
```C#
        internal void InvokeDraw()
        {
            var clip = false;
            if (Parent != null)
            {
                clip = true;
                Love.Graphics.Push();
                Love.Graphics.IntersectScissor(Parent.X, Parent.Y, Parent.W, Parent.H);
            }
            
            if (Renderer != null) Renderer.Draw(this);

            OnDraw(EventArgs.Empty);
            foreach (var c in Children)
            {
                c.InvokeDraw();
            }
            if (clip) Love.Graphics.Pop();
        }```

**Comment by endlesstravel** [comment]
For your information, i think you can deal with it by reset your Scissor to parent rectangle
change from
```C#
 if (clip) Love.Graphics.Pop(); 
```
to
```C#
 if (clip)   Love.Graphics.SetScissor(Parent.X, Parent.Y, Parent.W, Parent.H);
```

**Comment by Shadowblitz16** [comment]
hmm ok thankyou
